baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'E'
theme = "hugo-theme-console"

[params]
  [[params.links]]
    title = "Posts"
    url = "/posts"

  [[params.links]]
    title = "CV"
    url = "/cv.pdf"